### ISSUE TITLE
Proper way to create Gromacs-colvars release

### ISSUE THREAD

**Issue by HubLot** [Colvars/gromacs#1]
Hi,

Following https://github.com/Colvars/colvars/pull/190, I'm trying to set up the best way to create colvars patched gromacs archive through release/tags.

For now, here the steps (with an example on the branch `release-2020`)
  - create a copy branch  from a release on : `release-2020-colvars`
  - Apply colvars patch with the script `update-colvars-code.sh`
  - Commit the patch

Now, we have a release branch with the colvars modifications we could update with the new commits from upstream.

And, to create a release with a minor gromacs version (2020.1 for example):
  - Checkout to the tag : `git checkout tags/v2020.1`
  - Cherry pick the colvars patch commit : `git cherry-pick xxxx`
  - Create a new tag : `git tag -a v2020.1-colvars -m "Colvars patch for 2020.1` 
  - Come back to the branch : `git checkout -`
  - Push the new tag : `git push origin v2020.1-colvars`

The only downside is that the tag created for colvars is not in the history since it has been created on a detached head but i don't think it's problematic.

Maybe when created the commit and the tags message, we could specify the version of colvars (or the date) to easily identify when the patch has been created.

What do you think? @giacomofiorin @jhenin

**Comment by giacomofiorin** [comment]
It all looks okay to me overall.  I hadn't used so far annotated tags, but it would definitely be a good idea to do so, and include the Colvars version in the message.  The only thing that is really important in my opinion is having links to the relevant tags somewhere conveniently accessible. Perhaps the main webpage and the README of https://github.com/Colvars/colvars?  (Leaving the README of this repo as is).

I don't have any strong preferences for either way to organize the commit history.  There is a possible alternative where instead of cherry-picking the Colvars commit, you rebase the derived branch onto the original one:
```
git checkout release-2020-colvars
git rebase release-2020
```
But truly, I am fine with any way that the history looks like.  The original branches will not be merged back in, anyway.

One thing that I was thinking about: would you be open to splitting `colvarproxy_gromacs` in two tiers, i.e. a base class that contains code that is common to all GROMACS versions, and a derived one that is specific to a given release?  This may reduce the amount of duplicated code between versions, and help preventing conflicts between future updates to the library files and future updates from your branch.  Given the two-level inheritance, we can use `override` and `final` more.

Lastly, it may be useful for CMake to print the Colvars version when it is first run.

**Comment by giacomofiorin** [comment]
FYI for consistency this this repository I moved my LAMMPS clone to https://github.com/Colvars/lammps.

**Comment by HubLot** [comment]
> 
> 
> It all looks okay to me overall. I hadn't used so far annotated tags, but it would definitely be a good idea to do so, and include the Colvars version in the message. The only thing that is really important in my opinion is having links to the relevant tags somewhere conveniently accessible. Perhaps the main webpage and the README of https://github.com/Colvars/colvars? (Leaving the README of this repo as is).

Okay, I will redo the commit and tags with the colvars version printed.
Yes, the colvars README would be a good place. (Plus, it hasn't been uptaded with Gromacs support.) I will add also a HOW-TO for created patch versions in `devel-tools`.


> I don't have any strong preferences for either way to organize the commit history. There is a possible alternative where instead of cherry-picking the Colvars commit, you rebase the derived branch onto the original one:
> 
> ```
> git checkout release-2020-colvars
> git rebase release-2020
> ```
> But truly, I am fine with any way that the history looks like. The original branches will not be merged back in, anyway.

The rebase will keep the derivated branch updated but I'm not sure it will allow us to create a tag of patched versions at the same commit that a regular version (For 2020.1 for example, we need to patch the files at the same commit that the tag 2020.1 has been created).

> One thing that I was thinking about: would you be open to splitting `colvarproxy_gromacs` in two tiers, i.e. a base class that contains code that is common to all GROMACS versions, and a derived one that is specific to a given release? This may reduce the amount of duplicated code between versions, and help preventing conflicts between future updates to the library files and future updates from your branch. Given the two-level inheritance, we can use `override` and `final` more.

On the paper, I'm not opposed but I'm worried it will complicated the patching and the maintenance too much compared to the gain of less duplicated code. We could create an issue and a test branch on colvars git and see what it could looks like?

> 
> Lastly, it may be useful for CMake to print the Colvars version when it is first run.

You mean the gromacs cmake when building the software?

**Comment by jhenin** [comment]
> One thing that I was thinking about: would you be open to splitting colvarproxy_gromacs in two tiers, i.e. a base class that contains code that is common to all GROMACS versions, and a derived one that is specific to a given release? This may reduce the amount of duplicated code between versions, and help preventing conflicts between future updates to the library files and future updates from your branch. Given the two-level inheritance, we can use override and final more.

Maybe I'm missing something in your plan, but I'm unsure about the return on investment of this, given the added complexity in the short term.

Duplication of code between versions of the proxy are not a major issue to me, because those versions are not meant to be maintained indefinitely. In the long term older versions will be deprecated, and we'll only maintain interfaces to the newest Gromacs versions.

**Comment by giacomofiorin** [comment]
> Maybe I'm missing something in your plan, but I'm unsure about the return on investment of this, given the added complexity in the short term.

I was thinking about how to tackle future changes to the proxy that are cross-platform, such as the ability to dynamically unrequest and request atoms that I've been working on. 

> 
> Duplication of code between versions of the proxy are not a major issue to me, because those versions are not meant to be maintained indefinitely. In the long term older versions will be deprecated, and we'll only maintain interfaces to the newest Gromacs versions.

There is no perfect solution either way unfortunately. For the moment, let's go with what you and @HubLot think is best. We will have to perhaps reassess this as more changes upstream unfold.

**Comment by jhenin** [comment]
> I was thinking about how to tackle future changes to the proxy that are cross-platform, such as the ability to dynamically unrequest and request atoms that I've been working on.

In that respect, I'm absolutely in favor of separating out code that is common to several back-ends! The more work colvarproxy.cpp does, the less work we have on each interface.

**Comment by giacomofiorin** [comment]
Questions related to tags and releases are resolved.  Other development topics are at the [Colvars repository](https://github.com/Colvars/colvars) or at the [issue](https://gitlab.com/gromacs/gromacs/-/issues/3357) on the GROMACS repo.
